config/routes.rb
Rails.application.routes.draw do
  resources :companies do
    resources :hiring_managers
    resources :roles
  end
  resources :candidates
  devise_for :users, controllers: { registrations: 'registrations' }
  root to: 'homes#index'
end

app/models/hiring_manager.rb
class HiringManager < ApplicationRecord
  belongs_to :company
  belongs_to :user

  accepts_nested_attributes_for :user

  validates_presence_of  :position
end

app/controllers/hiring_managers_controller.rb
class HiringManagersController < ApplicationController
  before_action { authenticate 'advisor' }
  before_action :set_company
  before_action :set_hiring_manager, only: [:show, :edit, :update, :destroy]

  # GET /hiring_managers
  # GET /hiring_managers.json
  def index
    @hiring_managers = @company.hiring_managers.all
  end

  # GET /hiring_managers/1
  # GET /hiring_managers/1.json
  def show
  end

  # GET /hiring_managers/new
  def new
    @hiring_manager = HiringManager.new
    @hiring_manager.user = User.new
  end

  # GET /hiring_managers/1/edit
  def edit
  end

  # POST /hiring_managers
  # POST /hiring_managers.json
  def create
    @hiring_manager = HiringManager.new(hiring_manager_params)
    @hiring_manager.user.password = 'placeholder to be reset'
    @hiring_manager.company = @company
    if @hiring_manager.save
      redirect_to [@company, @hiring_manager], notice: 'Hiring manager was successfully created.'
    else
       render :new
      end
  end

  # PATCH/PUT /hiring_managers/1
  # PATCH/PUT /hiring_managers/1.json
  def update
    if @hiring_manager.update(hiring_manager_params)
      redirect_to [@company, @hiring_manager], notice: 'Hiring manager was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /hiring_managers/1
  # DELETE /hiring_managers/1.json
  def destroy
    @hiring_manager.destroy
      redirect_to company_hiring_managers_path(@company), notice: 'Hiring manager was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:company_id])
    end

    def set_hiring_manager
      @hiring_manager = @company.hiring_managers.includes(:user).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hiring_manager_params
      params.require(:hiring_manager).permit(:user_id, :company_id, :position,
          user_attributes: [:id, :first_name, :last_name, :email])
    end
end

app/helpers/hiring_managers_helper.rb
module HiringManagersHelper
end

app/views/hiring_managers/_form.html.erb
<%= form_for([company, hiring_manager]) do |f| %>
  <% if hiring_manager.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hiring_manager.errors.count, "error") %> prohibited this hiring_manager from being saved:</h2>

      <ul>
      <% hiring_manager.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.fields_for :user do |user| %>
        <%# todo move this to a user fields partial %>
      <%= user.hidden_field :id %>

      <div class="field">
        <%= user.label :first_name %>
        <%= user.text_field :first_name %>
      </div>

        <div class="field">
          <%= user.label :last_name %>
          <%= user.text_field :last_name %>
        </div>

        <div class="field">
          <%= user.label :email %>
          <%= user.email_field :email %>
        </div>
  <% end %>

  <div class="field">
    <%= f.label :position %>
    <%= f.text_field :position %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hiring_managers/edit.html.erb
<h1>Editing Hiring Manager</h1>

<%= render 'form', company: @company, hiring_manager: @hiring_manager %>

<%= link_to 'Show', [@company, @hiring_manager] %> |
<%= link_to 'Back', company_hiring_managers_path(@company) %>

app/views/hiring_managers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Hiring Managers for <%= @company.name %></h1>

<table>
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Email</th>
      <th>Position</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hiring_managers.each do |hiring_manager| %>
      <tr>
        <td><%= hiring_manager.user.first_name %></td>
        <td><%= hiring_manager.user.last_name %></td>
        <td><%= hiring_manager.user.email %></td>
        <td><%= hiring_manager.position %></td>
        <td><%= link_to 'Show', [@company, hiring_manager] %></td>
        <td><%= link_to 'Edit', edit_company_hiring_manager_path(@company, hiring_manager) %></td>
        <td><%= link_to 'Destroy', [@company, hiring_manager], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hiring Manager', new_company_hiring_manager_path(@company) %>

app/views/hiring_managers/new.html.erb
<h1>New Hiring Manager</h1>

<%= render 'form', company: @company, hiring_manager: @hiring_manager %>

<%= link_to 'Back', company_hiring_managers_path(@company) %>

app/views/hiring_managers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First Name:</strong>
  <%= @hiring_manager.user.first_name %>
</p>

<p>
  <strong>Last Name:</strong>
  <%= @hiring_manager.user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @hiring_manager.user.email %>
</p>

<p>
  <strong>Position:</strong>
  <%= @hiring_manager.position %>
</p>

<%= link_to 'Edit', edit_company_hiring_manager_path(@company, @hiring_manager) %> |
<%= link_to 'Back', company_hiring_managers_path(@company) %>