config/routes.rb
Rails.application.routes.draw do
  resources :companies do
    resources :hiring_managers
    resources :roles
  end
  resources :candidates
  devise_for :users, controllers: { registrations: 'registrations' }
  root to: 'homes#index'
end

app/models/candidate.rb
class Candidate < ApplicationRecord
  belongs_to :user
  has_one :resume, foreign_key: :user_id

  accepts_nested_attributes_for :resume


  validates_presence_of :first_name, :last_name, :email, :phone, :desired_position
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  before_action only: [:index, :destroy] { authenticate 'advisor' }
  before_action except: [:index, :destroy] { authenticate 'advisor', 'candidate' }
  before_action :set_candidate, only: [:show, :edit, :update, :destroy]

  # GET /candidates
  # GET /candidates.json
  def index
    @candidates = Candidate.all
  end

  # GET /candidates/1
  # GET /candidates/1.json
  def show
  end

  # GET /candidates/new
  def new
    @candidate = Candidate.new
    @candidate.resume = Resume.new
  end

  # GET /candidates/1/edit
  def edit
  end

  # POST /candidates
  # POST /candidates.json
  def create
    @candidate = Candidate.new(candidate_params)

    if @candidate.resume.resume_data.nil?
      @candidate.resume = nil
    else
      @candidate.resume.file_name, @candidate.resume.content_type, @candidate.resume.resume_data = extract_file(@candidate.resume.resume_data)
    end

    if current_user.role == 'candidate'
      @candidate.user = current_user
    else
      @candidate.user = User.new do
        first_name = @candidate.first_name,
        last_name = @candidate.last_name,
        email = @candidate.email
      end
    end

    if @candidate.save
       redirect_to (current_user.role == 'candidate' ? root_path : @candidate), notice: 'Candidate was successfully created.'
    else
        render :new
    end
  end

  # PATCH/PUT /candidates/1
  # PATCH/PUT /candidates/1.json
  def update
      if @candidate.update(candidate_params)
        redirect_to (current_user.role == 'candidate' ? root_path : @candidate), notice: 'Candidate was successfully updated.'
      else
        render :edit
      end
  end

  # DELETE /candidates/1
  # DELETE /candidates/1.json
  def destroy
    @candidate.destroy
    redirect_to candidates_url, notice: 'Candidate was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_candidate
      @candidate = Candidate.includes(:user, :resume).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def candidate_params
      params.require(:candidate).permit(:user_id, :first_name, :last_name, :email, :phone, :desired_position, :current_company, :linked_in_url, :twitter_url, :git_hub_url, :portfolio_url, :website_url,
          resume_attributes:[:resume_data])
    end

    def extract_file(file)
      return file.original_filename, file.content_type, file.read
    end
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/views/candidates/_form.html.erb
<%= form_for(candidate, multipart: true)   do |f| %>
  <% if candidate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(candidate.errors.count, "error") %> prohibited this candidate from being saved:</h2>

      <ul>
      <% candidate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>

  <div class="field">
    <%= f.label :phone %>
    <%= f.phone_field :phone %>
  </div>

  <div class="field">
    <%= f.label :desired_position %>
    <%= f.text_field :desired_position %>
  </div>

  <div class="field">
    <%= f.label :current_company %>
    <%= f.text_field :current_company %>
  </div>

  <div class="field">
    <%= f.label :linked_in_url %>
    <%= f.url_field :linked_in_url %>
  </div>

  <div class="field">
    <%= f.label :twitter_url %>
    <%= f.url_field :twitter_url %>
  </div>

  <div class="field">
    <%= f.label :git_hub_url %>
    <%= f.url_field :git_hub_url %>
  </div>

  <div class="field">
    <%= f.label :portfolio_url %>
    <%= f.url_field :portfolio_url %>
  </div>

  <div class="field">
    <%= f.label :website_url %>
    <%= f.url_field :website_url %>
  </div>

  <%= f.fields_for :resume do |r| %>
    <div class="field">
      <%= r.label :resume_data %>
      <%= r.file_field :resume_data %>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/candidates/edit.html.erb
<h1>Editing Candidate</h1>

<%= render 'form', candidate: @candidate %>

<% unless current_user.role == 'candidate' %>
  <%= link_to 'Show', @candidate %> |
  <%= link_to 'Back', candidates_path %>
<% end %>

app/views/candidates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Candidates</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Desired position</th>
      <th>Current company</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @candidates.each do |candidate| %>
      <tr>
        <td><%= candidate.first_name %></td>
        <td><%= candidate.last_name %></td>
        <td><%= candidate.email %></td>
        <td><%= candidate.phone %></td>
        <td><%= candidate.desired_position %></td>
        <td><%= candidate.current_company %></td>
        <td><%= link_to 'Show', candidate %></td>
        <td><%= link_to 'Edit', edit_candidate_path(candidate) %></td>
        <td><%= link_to 'Destroy', candidate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% unless @candidates.any? %>
    <p>There's no candidates yet</p>
<% end %>

<br>

<%# link_to 'New Candidate', new_candidate_path %>

app/views/candidates/new.html.erb
<h1>New Candidate</h1>

<%= render 'form', candidate: @candidate %>

<% unless current_user.role == 'candidate' %>
  <%= link_to 'Back', candidates_path %>
<% end %>

app/views/candidates/show.html.erb
<p id="notice"><%= notice %></p>

<h5>User Info</h5>
<p>
  <strong>First name:</strong>
  <%= @candidate.user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @candidate.user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @candidate.user.email %>
</p>

<h5>Candidate info</h5>

<p>
  <strong>First name:</strong>
  <%= @candidate.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @candidate.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @candidate.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @candidate.phone %>
</p>

<p>
  <strong>Desired position:</strong>
  <%= @candidate.desired_position %>
</p>

<p>
  <strong>Current company:</strong>
  <%= @candidate.current_company %>
</p>

<p>
  <strong>Linked in url:</strong>
  <%= @candidate.linked_in_url %>
</p>

<p>
  <strong>Twitter url:</strong>
  <%= @candidate.twitter_url %>
</p>

<p>
  <strong>Git hub url:</strong>
  <%= @candidate.git_hub_url %>
</p>

<p>
  <strong>Portfolio url:</strong>
  <%= @candidate.portfolio_url %>
</p>

<p>
  <strong>Website url:</strong>
  <%= @candidate.website_url %>
</p>

<%= link_to 'Edit', edit_candidate_path(@candidate) %> |
<%= link_to 'Back', candidates_path %>