config/routes.rb
Rails.application.routes.draw do
  resources :companies do
    resources :hiring_managers
    resources :roles
  end
  resources :candidates
  devise_for :users, controllers: { registrations: 'registrations' }
  root to: 'homes#index'
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :address
  has_many :hiring_managers, dependent: :destroy
  has_many :roles, dependent: :destroy

  accepts_nested_attributes_for :address

  validates_presence_of :name
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action { authenticate 'advisor' }
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
    @company.address = Address.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)
    if @company.save
      redirect_to @company, notice: 'Company was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
      if @company.update(company_params)
        redirect_to @company, notice: 'Company was successfully updated.'
      else
        render :edit
      end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
      redirect_to companies_url, notice: 'Company was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.includes(:address).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :cloudbase_url, :linkedin_url, :glassdoors_url,
                                      address_attributes:[:street_address1, :street_address2, :city, :county, :state, :country, :zip])
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_for(company) do |f| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

    <%= f.fields_for :address do |address| %>
      <div class="field">
        <%= address.label :street_address1 %>
        <%= address.text_field :street_address1 %>
      </div>

      <div class="field">
        <%= address.label :street_address2 %>
        <%= address.text_field :street_address2 %>
      </div>

      <div class="field">
        <%= address.label :city %>
        <%= address.text_field :city %>
      </div>

      <div class="field">
        <%= address.label :county%>
        <%= address.text_field :county %>
      </div>

      <div class="field">
        <%= address.label :state %>
        <%= address.text_field :state %>
      </div>

      <div class="field">
        <%= address.label :country %>
        <%= address.text_field :country %>
      </div>

      <div class="field">
        <%= address.label :zip%>
        <%= address.text_field :zip %>
      </div>
    <% end %>

  <div class="field">
    <%= f.label :cloudbase_url %>
    <%= f.text_field :cloudbase_url %>
  </div>

  <div class="field">
    <%= f.label :linkedin_url %>
    <%= f.text_field :linkedin_url %>
  </div>

  <div class="field">
    <%= f.label :glassdoors_url %>
    <%= f.text_field :glassdoors_url %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Companies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Cloudbase url</th>
      <th>Linkedin url</th>
      <th>Glassdoors url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= company.address.city %></td>
        <td><%= company.address.state %></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% unless @companies.any? %>
    <p>There's no companies yet</p>
<% end %>

<br>

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<p>
  <strong>Street Address 1:</strong>
  <%= @company.address.street_address1 %>
</p>

<p>
  <strong>Street Address 2:</strong>
  <%= @company.address.street_address2 %>
</p>

<p>
  <strong>City:</strong>
  <%= @company.address.city %>
</p>

<p>
  <strong>:County:</strong>
  <%= @company.address.county %>
</p>

<p>
  <strong>State:</strong>
  <%= @company.address.state %>
</p>

<p>
  <strong>Country:</strong>
  <%= @company.address.country %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @company.address.zip %>
</p>

<p>
  <strong>Cloudbase url:</strong>
  <%= @company.cloudbase_url %>
</p>

<p>
  <strong>Linkedin url:</strong>
  <%= @company.linkedin_url %>
</p>

<p>
  <strong>Glassdoors url:</strong>
  <%= @company.glassdoors_url %>
</p>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>
<%= link_to 'Hiring Managers', company_hiring_managers_path(@company), taget:'_blank' %>
<%= link_to 'Roles', company_roles_path(@company), taget:'_blank' %>