config/routes.rb
Rails.application.routes.draw do
  resources :companies do
    resources :hiring_managers
    resources :roles
  end
  resources :candidates
  devise_for :users, controllers: { registrations: 'registrations' }
  root to: 'homes#index'
end

app/models/role.rb
class Role < ApplicationRecord
  belongs_to :company
  belongs_to :hiring_manager

  validates_presence_of :company_id, :name
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_company
  before_action :set_role, only: [:show, :edit, :update, :destroy]

  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(role_params)
    @role.company = @company

    if @role.save
      redirect_to [@company, @role], notice: 'Role was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
    if @role.update(role_params)
      redirect_to [@company, @role], notice: 'Role was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role.destroy
    redirect_to company_roles_path(@company), notice: 'Role was successfully destroyed.'
    head :no_content
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:company_id])
    end

    def set_role
      @role = @company.roles.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def role_params
      params.require(:role).permit(:company_id, :hiring_manager_id, :name, :description, :min_rate, :max_rate, :employment_time, :employment_type, :contract_duration_in_months, :travel_type, :sponsors_visa, :city, :state)
    end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/roles/_form.html.erb
<%= form_for([company, role]) do |f| %>
  <% if role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
      <% role.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :company_id %>

  <div class="field">
    <%= f.label :hiring_manager_id %>
    <%= f.collection_select :hiring_manager_id, company.hiring_managers, :id, ->(m) { "#{m.user.first_name} #{m.user.last_name}" }, prompt: 'Select a hiring manager' %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :min_rate %>
    <%= f.number_field :min_rate %>
  </div>

  <div class="field">
    <%= f.label :max_rate %>
    <%= f.number_field :max_rate %>
  </div>

  <div class="field">
    <%= f.label :employment_time %>
    <%= f.select :employment_time, ['Full Time', 'Part Time'] %>
  </div>

  <div class="field">
    <%= f.label :employment_type %>
    <%= f.select :employment_type, %w(Permanent Contract) %>
  </div>

  <div class="field">
    <%= f.label :contract_duration_in_months %>
    <%= f.number_field :contract_duration_in_months %>
  </div>

  <div class="field">
    <%= f.label :travel_type %>
    <%= f.select :travel_type, ['No Travel', '25% Travel', '50% Travel', 'More than 50% Travel'] %>
  </div>

  <div class="field">
    <%= f.label :sponsors_visa %>
    <%= f.check_box :sponsors_visa %>
  </div>

  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>

  <div class="field">
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/roles/edit.html.erb
<h1>Editing Role</h1>

<%= render 'form', company: @company, role: @role %>

<%= link_to 'Show', [@company, @role] %> |
<%= link_to 'Back', company_roles_path(@company) %>

app/views/roles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Roles for <%= @company.name %></h1>

<table>
  <thead>
    <tr>
      <th>Company</th>
      <th>Hiring manager</th>
      <th>Name</th>
      <th>Min rate</th>
      <th>Max rate</th>
      <th>Employment time</th>
      <th>Employment type</th>
      <th>Sponsors visa</th>
      <th>City</th>
      <th>State</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @roles.each do |role| %>
      <tr>
        <td><%= role.company.name %></td>
        <td><%= role.hiring_manager&.user.first_name %> <%= role.hiring_manager&.user.last_name %></td>
        <td><%= role.name %></td>
        <td><%= role.min_rate %></td>
        <td><%= role.max_rate %></td>
        <td><%= role.employment_time %></td>
        <td><%= role.employment_type %></td>
        <td><%= role.sponsors_visa %></td>
        <td><%= role.city %></td>
        <td><%= role.state %></td>
        <td><%= link_to 'Show', [@company, role] %></td>
        <td><%= link_to 'Edit', edit_company_role_path(@company, role) %></td>
        <td><%= link_to 'Destroy', [@company, role], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Role', new_company_role_path(@company) %>

app/views/roles/new.html.erb
<h1>New Role</h1>

<%= render 'form', company: @company, role: @role %>

<%= link_to 'Back', company_roles_path(@company) %>

app/views/roles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Company:</strong>
  <%= @role.company.name %>
</p>

<p>
  <strong>Hiring manager:</strong>
  <%= @role.hiring_manager&.user.first_name %> <%= @role.hiring_manager&.user.last_name %>
</p>

<p>
  <strong>Name:</strong>
  <%= @role.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @role.description %>
</p>

<p>
  <strong>Min rate:</strong>
  <%= @role.min_rate %>
</p>

<p>
  <strong>Max:</strong>
  <%= @role.max_rate %>
</p>

<p>
  <strong>Employment time:</strong>
  <%= @role.employment_time %>
</p>

<p>
  <strong>Employment type:</strong>
  <%= @role.employment_type %>
</p>

<p>
  <strong>Contract Durtation(months):</strong>
  <%= @role.contract_duration_in_months %>
</p>

<p>
  <strong>Travel type:</strong>
  <%= @role.travel_type %>
</p>

<p>
  <strong>Sponsors visa:</strong>
  <%= @role.sponsors_visa %>
</p>

<p>
  <strong>City:</strong>
  <%= @role.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @role.state %>
</p>

<%= link_to 'Edit', edit_company_role_path(@company, @role) %> |
<%= link_to 'Back', company_roles_path(@company) %>